### ISSUE TITLE
concourse-terraform sample

### ISSUE THREAD

**Issue by hsok85** [hsok85/docs#2]
```
---
resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

resources:
- name: cf-terraform
  type: git
  check_every: 5m
  source:
    uri: ((oss-git-uri))
    branch: ((oss-git-branch))
    private_key: ((oss-git-key))
    paths:
    - terraform/global/((ENV))/*
    - terraform/global/((ENV))/**/*

jobs:

- name: plan-terraform
  serial: true
  build_logs_to_retain: 30
  plan:
  - aggregate:
    - get: cf-terraform
      trigger: true
  - task: deploy
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: 
          repository: regi-eu.seasam.org:443/devops-terraform
          tag: latest
          username: ((docker-regi-user))
          password: ((docker-regi-password))
      params:
        REGION: ((REGION))
        ENV: ((ENV))
        VAULT_ADDR: ((VAULT_ADDR))
        VAULT_TOKEN: ((VAULT_TOKEN))
        VAULT_SKIP_VERIFY: "true"
      inputs:
        - name: cf-terraform
      outputs:
        - name: updated-cf-terraform
      run:
        path: sh
        args:
        - -exc
        - |
          set +x
          export AWS_ACCESS_KEY_ID=`safe get secret/${REGION}/${ENV}/aws/ansible/access_key:value`
          export AWS_SECRET_ACCESS_KEY=`safe get secret/${REGION}/${ENV}/aws/ansible/secret_key:value`
          export AWS_DEFAULT_REGION=`safe get secret/${REGION}/${ENV}/aws/ansible/aws_region:value`
          set -x
          cd cf-terraform
          cd terraform/global/${ENV}
          terraform init -backend=true -backend-config="access_key=${AWS_ACCESS_KEY_ID}" -backend-config="secret_key=${AWS_SECRET_ACCESS_KEY}"
          sh ./terraform.sh plan

- name: output-terraform
  serial: true
  build_logs_to_retain: 30
  plan:
  - aggregate:
    - get: cf-terraform
      passed: [apply-terraform]
      trigger: true
  - task: deploy
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: 
          repository: regi-eu.seasam.org:443/devops-terraform
          tag: latest
          username: ((docker-regi-user))
          password: ((docker-regi-password))
      params:
        REGION: ((REGION))
        ENV: ((ENV))
        VAULT_ADDR: ((VAULT_ADDR))
        VAULT_TOKEN: ((VAULT_TOKEN))
        VAULT_SKIP_VERIFY: "true"
      inputs:
        - name: cf-terraform
      outputs:
        - name: updated-cf-terraform
      run:
        path: sh
        args:
        - -exc
        - |
          set +x
          export AWS_ACCESS_KEY_ID=`safe get secret/${REGION}/${ENV}/aws/ansible/access_key:value`
          export AWS_SECRET_ACCESS_KEY=`safe get secret/${REGION}/${ENV}/aws/ansible/secret_key:value`
          export AWS_DEFAULT_REGION=`safe get secret/${REGION}/${ENV}/aws/ansible/aws_region:value`
          set -x
          cd cf-terraform
          cd terraform/global/${ENV}
          terraform init -backend=true -backend-config="access_key=${AWS_ACCESS_KEY_ID}" -backend-config="secret_key=${AWS_SECRET_ACCESS_KEY}"
          terraform output

- name: apply-terraform
  serial: true
  build_logs_to_retain: 30
  plan:
  - aggregate:
    - get: cf-terraform
      passed: [plan-terraform]
  - task: deploy
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: 
          repository: regi-eu.seasam.org:443/devops-terraform
          tag: latest
          username: ((docker-regi-user))
          password: ((docker-regi-password))
      params:
        REGION: ((REGION))
        ENV: ((ENV))
        VAULT_ADDR: ((VAULT_ADDR))
        VAULT_TOKEN: ((VAULT_TOKEN))
        VAULT_SKIP_VERIFY: "true"
      inputs:
        - name: cf-terraform
      outputs:
        - name: updated-cf-terraform
      run:
        path: sh
        args:
        - -exc
        - |
          set +x
          export AWS_ACCESS_KEY_ID=`safe get secret/${REGION}/${ENV}/aws/ansible/access_key:value`
          export AWS_SECRET_ACCESS_KEY=`safe get secret/${REGION}/${ENV}/aws/ansible/secret_key:value`
          export AWS_DEFAULT_REGION=`safe get secret/${REGION}/${ENV}/aws/ansible/aws_region:value`
          set -x
          cd cf-terraform
          cd terraform/global/${ENV}
          terraform init -backend=true -backend-config="access_key=${AWS_ACCESS_KEY_ID}" -backend-config="secret_key=${AWS_SECRET_ACCESS_KEY}"
          sh ./terraform.sh apply -auto-approve 

```
