### ISSUE TITLE
gitlab ci sample

### ISSUE THREAD

**Issue by hsok85** [hsok85/docs#8]
```
include:
  # Terraform jobs
  - local: /gitlab-ci-jobs/jobs-hcp-devops-prd-terraform.yml
  - local: /gitlab-ci-jobs/jobs-hcp-devops-stg-terraform.yml
  - local: /gitlab-ci-jobs/jobs-hcp-cmp-prd-terraform.yml
  - local: /gitlab-ci-jobs/jobs-hcp-cmp-stg-terraform.yml
  - local: /gitlab-ci-jobs/jobs-hcp-log-prd-terraform.yml
  - local: /gitlab-ci-jobs/jobs-hcp-log-stg-terraform.yml
  - local: /gitlab-ci-jobs/jobs-hcp-lpp-prd-terraform.yml

stages:
  - validate           # feature, stage branches,
  - plan report        # merge request
  - plan               # push to master
  - landingzone        # push to master 
  - network            # push to master
  - server             # push to master 
  - database           # push to master 
  - k8s devops backend # push to master
  - k8s devops         # push to master
  - destroy

variables:
  PLAN: plan.tfplan
  JSON_PLAN_FILE: tfplan.json

.set-exec-location: &set-exec-location
  - LOCATION=$(echo $CI_JOB_NAME | cut -d":" -f3)
  - cd $LOCATION

.set-spin-name: &set-spin-name
  - SPIN_NAME=$(echo spin-`echo $CI_JOB_NAME | cut -d "/" -f4`)

.vault-login: &vault-login
  - VAULT_TOKEN=$(vault write -field token auth/approle/login role_id=$VAULT_APPROLE_ROLE_ID secret_id=$VAULT_APPROLE_SECRET_ID)
  - vault login $VAULT_TOKEN

.install-package: &install-package
  - alias convert_report="jq -r '([.resource_changes[].change.actions?]|flatten)|{\"create\":(map(select(.==\"create\"))|length),\"update\":(map(select(.==\"update\"))|length),\"delete\":(map(select(.==\"delete\"))|length)}'"

.set-secret: &set-secret 
  # git configuration
  - |
    git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab".insteadOf https://gitlab
  
  # Terraform secret variables (IaC master key set)
  - |
    export TF_VAR_aws_access_key_id=$AWS_ACCESS_KEY_ID
    export TF_VAR_aws_secret_access_key=$AWS_SECRET_ACCESS_KEY
    
    export TF_VAR_thanos_s3_access_key=$THANOS_AWS_ACCESS_KEY_ID
    export TF_VAR_thanos_s3_secret_key=$THANOS_AWS_SECRET_ACCESS_KEY
    
    export TF_VAR_thanos_stg_s3_access_key=$THANOS_STG_AWS_ACCESS_KEY_ID
    export TF_VAR_thanos_stg_s3_secret_key=$THANOS_STG_AWS_SECRET_ACCESS_KEY
    
    export TF_VAR_fluentd_access_key=$FLUENTD_AWS_ACCESS_KEY_ID
    export TF_VAR_fluentd_secret_key=$FLUENTD_AWS_SECRET_ACCESS_KEY
    
    export TF_VAR_fluentd_stg_access_key=$FLUENTD_STG_AWS_ACCESS_KEY_ID
    export TF_VAR_fluentd_stg_secret_key=$FLUENTD_STG_AWS_SECRET_ACCESS_KEY
    export TF_VAR_prometheus_basic_auth_info=$PROMETHEUS_BASIC_AUTH_INFO
    export TF_VAR_prd_oidc_client_id=$GRAFANA_PRD_OIDC_CLIENT_ID
    export TF_VAR_prd_oidc_client_secret=$GRAFANA_PRD_OIDC_CLIENT_SECRET
    export TF_VAR_stg_oidc_client_id=$GRAFANA_STG_OIDC_CLIENT_ID
    export TF_VAR_stg_oidc_client_secret=$GRAFANA_STG_OIDC_CLIENT_SECRET

  # IAM assume-role setting
  - |
    ACCOUNT=$(echo $CI_JOB_NAME | cut -d":" -f2)
    IAC_ROLE=$(aws sts assume-role --role-arn "arn:aws:iam::$ACCOUNT:role/DevopsIacAccessRole" --duration-seconds 3600 --role-session-name AWSCLI-Session)
    export AWS_ACCESS_KEY_ID=$(echo $IAC_ROLE | jq -r '.Credentials.AccessKeyId')
    export AWS_SECRET_ACCESS_KEY=$(echo $IAC_ROLE | jq -r '.Credentials.SecretAccessKey')
    export AWS_SESSION_TOKEN=$(echo $IAC_ROLE | jq -r '.Credentials.SessionToken')

.check-terraform: &check-terraform
  - terraform --version
  - terraform init

.terraform_template:
  image: registry.h-firework.com/devsecops/hanwha-terraform:v1.0.9
  before_script:
    - *install-package
    - *vault-login

    # get devops master user IaC secrets from Vault
    - source ./gitlab-ci-jobs/vault-get-kv.sh AWS_ACCESS_KEY_ID hcp-devops-iam/awssso aws_access_key_id
    - source ./gitlab-ci-jobs/vault-get-kv.sh AWS_SECRET_ACCESS_KEY hcp-devops-iam/awssso aws_secret_access_key
    # get thanos prd secrets from Vault
    - source ./gitlab-ci-jobs/vault-get-kv.sh THANOS_AWS_ACCESS_KEY_ID hcp-devops-iam/thanos aws_access_key_id
    - source ./gitlab-ci-jobs/vault-get-kv.sh THANOS_AWS_SECRET_ACCESS_KEY hcp-devops-iam/thanos aws_secret_access_key
    # get thanos stg secrets from Vault
    - source ./gitlab-ci-jobs/vault-get-kv.sh THANOS_STG_AWS_ACCESS_KEY_ID hcp-devops-iam/thanos aws_access_key_id_stg
    - source ./gitlab-ci-jobs/vault-get-kv.sh THANOS_STG_AWS_SECRET_ACCESS_KEY hcp-devops-iam/thanos aws_secret_access_key_stg
    # get fluentd prd secrets from Vault
    - source ./gitlab-ci-jobs/vault-get-kv.sh FLUENTD_AWS_ACCESS_KEY_ID hcp-devops-iam/fluentd aws_access_key_id
    - source ./gitlab-ci-jobs/vault-get-kv.sh FLUENTD_AWS_SECRET_ACCESS_KEY hcp-devops-iam/fluentd aws_secret_access_key
    # get fluentd stg secrets from Vault
    - source ./gitlab-ci-jobs/vault-get-kv.sh FLUENTD_STG_AWS_ACCESS_KEY_ID hcp-devops-iam/fluentd aws_access_key_id_stg
    - source ./gitlab-ci-jobs/vault-get-kv.sh FLUENTD_STG_AWS_SECRET_ACCESS_KEY hcp-devops-iam/fluentd aws_secret_access_key_stg
    # get prometheus stg secrets from Vault
    - source ./gitlab-ci-jobs/vault-get-kv.sh PROMETHEUS_BASIC_AUTH_INFO hcp-devops-iam/prometheus prometheus_basic_auth_info
    # get grafana prd oidc client id/secret from Vault
    - source ./gitlab-ci-jobs/vault-get-kv.sh GRAFANA_PRD_OIDC_CLIENT_ID hcp-devops-iam/grafana prd_oidc_client_id
    - source ./gitlab-ci-jobs/vault-get-kv.sh GRAFANA_PRD_OIDC_CLIENT_SECRET hcp-devops-iam/grafana prd_oidc_client_secret
    # get grafana stg oidc client id/secret from Vault
    - source ./gitlab-ci-jobs/vault-get-kv.sh GRAFANA_STG_OIDC_CLIENT_ID hcp-devops-iam/grafana stg_oidc_client_id
    - source ./gitlab-ci-jobs/vault-get-kv.sh GRAFANA_STG_OIDC_CLIENT_SECRET hcp-devops-iam/grafana stg_oidc_client_secret

    - *set-secret
    - *set-exec-location
    - *check-terraform

.terraform_validate_template:
  stage: validate
  extends: .terraform_template
  script:
    - terraform validate
    - terraform fmt -check=true
  only:
    refs:
      - branches
  except:
    refs:
      - master

.terraform_plan_report_template:
  stage: plan report
  extends: .terraform_template
  script:
    - terraform plan -out=$PLAN
    - "terraform show --json $PLAN | convert_report > $CI_PROJECT_DIR/$JSON_PLAN_FILE"
  artifacts:
    expire_in: 1 week
    name: plan
    reports:
      terraform: $JSON_PLAN_FILE
  only:
    refs:
      - merge_requests

.terraform_plan_template:
  stage: plan
  extends: .terraform_template
  script:
    - terraform plan
  only:
    refs:
      - master

.terraform_apply_template:
  extends: .terraform_template
  script:
    - terraform apply -auto-approve
  only:
    refs:
      - master
  when: manual

.terraform_destroy_template:
  extends: .terraform_template
  script:
    - terraform destroy -auto-approve
  when: manual
```
